# Generated by Django 4.1.2 on 2023-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='promoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeName', models.CharField(max_length=1000, verbose_name='Название промокода')),
                ('userId', models.IntegerField(max_length=1000, null=True, verbose_name='ID пользователя')),
                ('limits', models.IntegerField(max_length=1000, verbose_name='Количество запросов')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен')),
                ('activationDate', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Промо-код',
                'verbose_name_plural': 'Промо-коды',
            },
        ),
    ]
