# Generated by Django 4.1.2 on 2023-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='limits',
            field=models.IntegerField(verbose_name='Количество запросов'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='userId',
            field=models.IntegerField(null=True, verbose_name='ID пользователя'),
        ),
    ]
